# Generated by Django 2.1.4 on 2018-12-17 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='文章id')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='网址')),
                ('brief', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='简述')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('columnId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='栏目id')),
                ('name', models.CharField(max_length=256, verbose_name='栏目名称')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='栏目网址')),
                ('intro', models.TextField(default='', verbose_name='栏目简介')),
            ],
            options={
                'verbose_name': '栏目',
                'verbose_name_plural': '栏目',
                'db_table': 'column',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('contentId', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='文章id')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('articleId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
                'db_table': 'content',
                'ordering': ['articleId'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='articles.Column', verbose_name='所属栏目'),
        ),
    ]
