# Generated by Django 2.1.4 on 2018-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='articleId',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
