# Generated by Django 2.1.4 on 2018-12-17 16:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181217_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='column',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='栏目简介'),
        ),
    ]
